all: all-xframe

install: install-xframe

clean: clean-xframe

all-xframe:
	(export PATH="$(PATH)" && cd xframe && make -w all)

install-xframe:
	(export PATH="$(PATH)" && cd xframe && make -w install)

clean-xframe:
	(export PATH="$(PATH)" && cd xframe && make -w clean)

